on: push
name: on push
jobs: 
   giHubActionForPytest:
     name: Github Action Pytest
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@master
       - name: GitHub Action Pytest
         uses: cclauss/GitHub-Action-for-pytest@master
         with:
            args: pytest