on: push
name: on push
jobs: 
  gitHubActionForPytest:
    name: GitHub Action for Pytest
    runs-on: Ubuntu-latest
    steps:
      - uses: action/checkout@master
      - name: GitHub Action for Pytest
        uses: cclauss/GitHub-Action-for-Pytest
        with:
          args: pytest
